---
abstract: 'DSL sugar for MongoDB'
author:
  - 'Pan Fan(nightsailer) <nightsailer at gmail dot com>'
build_requires:
  Test::Deep: 0.106
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MongoX
requires:
  Carp: 0
  MongoDB: 0.38
  parent: 0
resources:
  repository: http://github.com/nightsailer/mongo-x
version: 0.05
